version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.5.0
    environment:
      TZ: /usr/share/zoneinfo/Asia/Tokyo
    steps:
      - checkout

      - restore_cache:
         key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn

      - save_cache:
         paths:
           - node_modules
         key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test
