// TODO: あとで色々変更する

export const CHANGE_SEARCH_WORD = 'CHANGE_SEARCH_WORD';
export const REQUEST_PROCESS = 'REQUEST_PROCESS';
export const SUCCESS_SEARCH = 'SUCCESS_SEARCH';
export const FAILED_SEARCH = 'FAILED_SEARCH';
export const CHANGE_ALERT_MESSAGE = 'CHANGE_ALERT_MESSAGE';